# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Palculator Dev
tagline:          "Logbook"
description:      "Prosecutedt to the full extent of the jam."
url:              https://palculator.github.io/
baseurl:          ""

author:
  name:           'Palculator'
  url:            https://twitter.com/Palculator

paginate:         20
plugins:          [jekyll-paginate]
