# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Signaltonsalat Dev
tagline:          "Logbook"
description:      "Prosecutedt to the full extent of the jam."
url:              https://signaltonsalat.github.io/
baseurl:          ""

author:
  name:           'Signaltonsalat'
  url:            https://twitter.com/Signaltonsalat

paginate:         20
plugins:          [jekyll-paginate]
